pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws_jenkins_connection')
        AWS_SECRET_ACCESS_KEY = credentials('aws_jenkins_connection')
        AWS_DEFAULT_REGION = ('us-east-1')
    }
    stages {
        stage('Cloudformation') {
            steps {
             sh "aws cloudformation create-stack --template-body 'file:///var/lib/jenkins/workspace/Finishlinelab4_finishlinelab4/Finishlinelab4/finishlinelab4infra.yml' --stack-name 'FinislineLab4' --region 'us-east-1' --parameters ParameterKey=KeyName,ParameterValue=Finishlinelab.pem ParameterKey=InstanceType,ParameterValue=t2.small ParameterKey=DBName,ParameterValue=wordpress ParameterKey=DBUser,ParameterValue=wordpress ParameterKey=DBPassword,ParameterValue=2Twolove$ ParameterKey=DBRootPassword,ParameterValue=3Threelove$'"
        stage('AWS build') {'"
            }
        }
        stage('Build') {
            steps {
                echo 'Buildings..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}